name: 'Emoji Issue Classifier'
description: 'Automatically classifies GitHub issues and labels them with emojis'
author: 'Pedro Lopez'
branding:
  icon: 'dependabot'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
outputs:
  result:
    description: 'Result of the classification'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r classifier/requirements.txt
      shell: bash
    - name: Run classifier
      run: |
        python classifier/main.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
