name: 'Emoji Issue Classifier'
description: 'Automatically classifies GitHub issues and labels them with emojis'
author: 'Pedro Lopez'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
outputs:
  result:
    description: 'Result of the classification'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_EVENT_PATH: ${{ github.event_path }}
